version: '3.7'

volumes:
  prometheus: {}
  alertmanager: {}
  alertmanager-config: {}

configs:
   dockerd_config:
    file: ./dockerd-exporter/Caddyfile
   blackbox_config:
    file: ./blackbox/blackbox.yml
   prom_conf:
    file: ./prometheus/conf/prometheus.yml
   node_exporter_entrypoint:
    file: ./node-exporter/docker-entrypoint.sh
   alert_conf:
     file: ./prometheus/conf/alert.rules.yml
   node_rules:
    file: ./prometheus/conf/swarm_node.rules.yml
   task_rules:
    file: ./prometheus/conf/swarm_task.rules.yml
   
services:
  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /etc/hostname:/etc/nodename
    configs:
      - source: node_exporter_entrypoint 
        target: /docker-entrypoint.sh
    deploy:
      mode: global
    environment:
      - NODE_ID={{.Node.ID}}
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/home/'
      - '--collector.meminfo_numa'
      - '--no-collector.ipvs'
    entrypoint:
       - /bin/sh
       - /docker-entrypoint.sh

  dockerd-exporter:
    image: stefanprodan/caddy
    environment:
      - docker_gwbridge_IP=172.18.0.1
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: global
  
  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    configs:
      - source: blackbox_config
        target: /etc/blackbox/blackbox.yml
    volumes:
      - blackbox:/blackbox
    deploy:
      mode: global
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: prom_conf
        target: /etc/prometheus/prometheus.yml
      - source: alert_conf
        target: /etc/prometheus/alert.rules.yml
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.qa-docker-1==true"
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
        - "9093:9093"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.qa-docker-1==true"
    volumes:
      - alertmanager:/alertmanager
      - alertmanager-config:/etc/alertmanager
      
networks:
 default:
   external:
     name: nextracker-back
