global:
  scrape_interval:     15s
  evaluation_interval: 15s  
  
  external_labels:
    monitor: 'prommon'

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
      - targets: ['172.21.193.10:9090']  
  
  - job_name: 'dockerd-exporter'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323  
  
  - job_name: 'cadvisor'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080  
  
  - job_name: 'node-exporter'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
