global:
  scrape_interval:     15s
  evaluation_interval: 15s  
  
  external_labels:
    monitor: 'prommon'
    
rule_files:
  - alert.rules.yml
  - swarm_node.rules.yml
  - swarm_task.rules.yml
  
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'
      
scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']  
      
  - job_name: 'nginx-exporter'
    honor_labels: true
    static_configs:
      - targets: ['tatooine_nginx:9113','user-management_nginx:9113','tracker-ops-angular_nginx:9113','external-trackerops-landing-page_nginx:9113','matrix_nginx:9113']
    
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://task-tracker-ops-angular:80
        - http://task-tatooine:80
        - http://external-trackerops-landing-page:80
        - http://naboo_task-tatooine:80
        - http://user-management:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
    
  - job_name: 'dockerd-exporter'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323  
  
  - job_name: 'cadvisor'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080  
  
  - job_name: 'node-exporter'
    honor_labels: true
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
